### ISSUE TITLE
Bug Report: Eggnog crashes in Freeplay

### ISSUE THREAD

**Issue by SpunBlue** [thepercentageguy/FNFSharp#2]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [X] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
SC542

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Run Eggnog in Freeplay

## Please describe your issue. Provide extensive detail and images if possible.
Just launched Eggnog in Freeplay and it died

### Opened the Game in the Terminal so i can do this lol
source/engine/io/Modding.hx:67: ./assets/songs/eggnog/Inst.ogg=>true
source/engine/io/Modding.hx:70: Found file in normal assets: eggnog
source/states/menu/FreeplayState.hx:254: eggnog-hard
source/states/menu/FreeplayState.hx:261: CUR WEEK5
source/engine/functions/Conductor.hx:59: new BPM map BUDDY []
source/engine/io/Modding.hx:43: Looking for mod of name: 
source/engine/io/Modding.hx:135: Seeking included lib: week6
source/engine/io/Modding.hx:146: Seeking forced lib: week5
source/engine/io/Modding.hx:149: Found file in forced lib: week5
source/engine/io/Modding.hx:43: Looking for mod of name: 
source/engine/io/Modding.hx:135: Seeking included lib: week6
source/engine/io/Modding.hx:146: Seeking forced lib: week5
source/engine/io/Modding.hx:149: Found file in forced lib: week5
source/engine/io/Modding.hx:43: Looking for mod of name: 
source/engine/io/Modding.hx:135: Seeking included lib: week6
source/engine/io/Modding.hx:146: Seeking forced lib: week5
source/engine/io/Modding.hx:149: Found file in forced lib: week5

haxe.xml.XmlParserException: Unexpected end at line 93 char 27
Error : haxe.xml.XmlParserException: Unexpected end at line 93 char 27

**Comment by thepercentageguy** [comment]
damn sounds like a problem with some week 5 XML

**Comment by thepercentageguy** [comment]
shit corrupted
