### ISSUE TITLE
[Bug]: Incorrect layering in chart editor

### ISSUE THREAD

**Issue by dylanisreal** [thepercentageguy/FNFSharp#4]
### Platform

Windows

### What happened?

![image](https://user-images.githubusercontent.com/99680432/175384324-f3802956-d174-4908-b6b8-577d223f0b03.png)
the button is above the character thing
![image](https://user-images.githubusercontent.com/99680432/175384384-4d036178-bbde-49c8-b940-db0a1342a635.png)
and when selected it becomes even more cursed

### Steps to reproduce

Go to the chart editor, click on the character selection and the bug is there.

### Relevant Console Logs

none

### Version

1.4.0-PRE

**Comment by thepercentageguy** [comment]
fixed with https://github.com/thepercentageguy/FNFSharp/commit/ea950d71ced88571c5edd0c1287717a529670c6a
