### ISSUE TITLE
[Bug]: Crash on chart editor

### ISSUE THREAD

**Issue by dylanisreal** [thepercentageguy/FNFSharp#7]
### Platform

Windows

### What happened?

i just paused the chart editor while the song was still playing, when i came back the song suddenly got sped up and eventually crashed the game.

### Steps to reproduce

1. Go to chart editor
2. Place a note anywhere
3. click space button before the note
4. when note is hit, pause the game (just click out or smth)
5. come back and it'll crash.

### Version

1.4.0-PRE

**Comment by thepercentageguy** [comment]
I can't replicate the bug.
